repos:
- repo: https://github.com/astral-sh/ruff-pre-commit
  # Ruff version.
  rev: v0.13.0
  hooks:
    # Run the linter.
    - id: ruff-check
      args: [ --fix ]
      types_or: [ python ]
    # Run the formatter.
    - id: ruff-format
      types_or: [ python ]