version: '3.8'

services:
  closet-api:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./images:/app/images
      - ./logs:/app/logs
    environment:
      - FLASK_ENV=production
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    # Uncomment if you need to set Google AI API key
    # environment:
    #   - GOOGLE_API_KEY=your_api_key_here

  closet-frontend:
    build: ./frontend
    ports:
      - "3001:80"
    depends_on:
      - closet-api
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
