version: '3.8'

services:
  closet-api:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./images:/app/images
      - ./logs:/app/logs
      - ./data:/app/data
    environment:
      - FLASK_ENV=development
      - PYTHONUNBUFFERED=1
      - GEMINI_API_KEY=${GEMINI_API_KEY}
    restart: unless-stopped

  closet-frontend:
    build: 
      context: ./frontend
      target: development
    ports:
      - "3001:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    depends_on:
      - closet-api
    restart: unless-stopped
